export const RFC822 = 'ddd, DD MMM YYYY HH:mm:ss ZZ'
export const DOWNLOADS_DIR = 'static/downloads'
export const RSS_DIR       = 'static/downloads/rss'
export const COVER_DIR     = 'static/downloads/cover'
export const BUILD_INFO    = 'static/downloads/build_info.json'
